global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Файлы с правилами алертов
rule_files:
  - "/etc/prometheus/alerts.yml"

# Конфигурация scrape targets
scrape_configs:
  # Node Exporters
  - job_name: 'node-exporters'
    static_configs:
      - targets: 
          - 'node_exporter_web:9100'
          - 'node_exporter_mon:9100'
        labels:
          env: 'production'
    metrics_path: /metrics
    scrape_interval: 30s

  # Self-monitoring Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics

  # Alertmanager monitoring
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    metrics_path: /metrics

  # MySQL monitoring
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld_exporter:9104']
    metrics_path: /metrics
    params:
      collect[]:
        - global_status
        - global_variables
        - slave_status
        - info_schema.processlist
        - engine_innodb_status

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # Blackbox exporter - внутренние HTTP
  - job_name: 'blackbox-http-internal'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://nginx:80
          - http://python_app:8000
          - http://wordpress:9000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox_exporter:9115'
    scrape_interval: 30s

  # Blackbox exporter - внешние HTTP
  - job_name: 'blackbox-http-external'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://192.168.56.10:80
          - http://192.168.56.10:443
          - http://192.168.56.20:3001
          - http://192.168.56.20:9091
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox_exporter:9115'
    scrape_interval: 1m

  # Blackbox TCP проверки
  - job_name: 'blackbox-tcp-internal'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - database:3306
          - nginx:443
          - rsyslog:514
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox_exporter:9115'
    scrape_interval: 30s

  # Мониторинг Blackbox exporter
  - job_name: 'blackbox-exporter'
    static_configs:
      - targets: ['blackbox_exporter:9115']
    metrics_path: /metrics

  # Rsyslog monitoring
  - job_name: 'rsyslog'
    static_configs:
      - targets: ['rsyslog:9100']
    metrics_path: /metrics

# Настройки Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      scheme: http
      timeout: 10s
      api_version: v2