groups:
  - name: example
    rules:
      - alert: HighRequestLatency
        expr: job:request_latency_seconds:mean5m{job="nginx"} > 0.5
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "High request latency on {{ $labels.instance }}"