---
- name: Update apt cache (Debian)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Install base packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present
  vars:
    ansible_package_mgr: "{{ 'apt' if ansible_os_family == 'Debian' else 'yum' }}"