---
- name: Deploy SSH authorized keys
  ansible.builtin.copy:
    src: authorized_keys
    dest: /root/.ssh/authorized_keys
    mode: '0600'
    owner: root
    group: root
  when: ansible_distribution != "Container Linux by CoreOS"

- name: Configure SSH daemon
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: '0600'
    validate: '/usr/sbin/sshd -t -f %s'
  notify: restart sshd

- name: Set MOTD
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    mode: '0644'