---
- name: Установить зависимости
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: yes

- name: Добавить ключ Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Добавить репозиторий Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Установить Docker и Compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Убедиться, что Docker запущен
  service:
    name: docker
    state: started
    enabled: yes
